---
title: "Practical 2"
format: html 
---


```{r}
#| echo =FALSE
#| 
pkg_vec <- c("ggplot2", "palmerpenguins", "ggthemes")
for (x in pkg_vec) {
  if (!requireNamespace(x, quietly = TRUE)) {
    install.packages(x, dependencies = TRUE)
  }
  # if you want to programmatically attach
  # libraries, this is the way to to do it
  library(x, character.only = TRUE)
}

projrsimple::projr_init()
library(ggplot2)
library(dplyr)


```

Question 1: Set your seed 
```{r}

#|echo: TRUE
## Setting the seed to 1
set.seed(1) 

## Creating a numeric vector called x and the function y using the sine wave
x <- 1:100
y <-  sin(x/10) + rnorm(100 ,mean=0, sd=0.2)
```


Question 2: CustomLowess
```{r}
#| echo: TRUE
customLowess <- function(x,y,f) {
  
  ##distance between the x values
  num <- length(x)
  k <- f*n
  
  for (i in 1:num) {
    distance_x = abs(x-x[i])
    
  }
  
}
```

```{r}
f <- 0.4
built_in <- lowess(x,y,iter=0)
built_in
```


```{r}
## Plot
f <- 0.1
data_frame <- as.data.frame(built_in)
ggplot(data = data_frame,mapping = aes(x, y), header = "Plot of Lowess Smoothing") + geom_point() + geom_smooth(method= "lm")


```

